version: '3.5'
services:
  1172-db:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./SQL/Ascension.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ascension
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - internal-net
    container_name: 1172-db
  1172-app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    restart: always
    depends_on:
      - "1172-db"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      WAIT_HOSTS: 1172-db:3306
    ports:
      - '7575:7575'
      - '7576:7576'
      - '7577:7577'
      - '7578:7578'
      - '8484:8484'
    expose:
      - '7575'
      - '7576'
      - '7577'
      - '7578'
      - '8484'
    networks:
      - internal-net
    container_name: 1172-app
networks:
  internal-net:
    name: internal-net
